Homework 3
iRezograf/Rafael_Reziapov pull request #10
Opened 2021-05-15 13:35 UTC by iRezograf

Refactoring done

2021-05-15 18:57 UTC, shoggy requested changes

2021-05-15 18:57 UTC, shoggy commented on src/test/java/ru/training/at/hw3/pageobjects/LoginPage.java
> +        wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//*[@id='user-name']")));
To get rid of locator duplicating, please replace it with other expected condition
```suggestion
        wait.until(ExpectedConditions.visibilityOf(loggedUserName));
```

2021-05-15 18:57 UTC, shoggy commented on src/test/java/ru/training/at/hw3/pageobjects/DifferentElementsPage.java
> +    WebElement stringWater;
Please replace these by one `List<WebElements>` that contains all log lines

2021-05-15 18:57 UTC, shoggy commented on src/test/java/ru/training/at/hw3/pageobjects/DifferentElementsPage.java
> +    }
This method should return `List<String>` from a new field that contains all log lines

2021-05-15 18:57 UTC, shoggy commented on src/test/java/ru/training/at/hw3/pageobjects/BenefitText.java
> +    WebElement benefitBase;
Please replace it with one `List<WebElement>` that contains all benefit texts
As a reference please use locator from `fourTextsOnTheIndexPageUnderIconsAndTheyHaveProperTextTest()` of hw2

2021-05-15 18:57 UTC, shoggy commented on src/test/java/ru/training/at/hw3/pageobjects/BenefitText.java
> +    }
These methods should be replaced by one returning `List<String>` from a new filed that contains all benefit texts

2021-05-15 18:57 UTC, shoggy commented on src/test/java/ru/training/at/hw3/pageobjects/BenefitIcon.java
> +    private WebElement benefitBase;
You need only the count of icons, so please replace it with one `List<WebElement>` without defining of specific benefit types

2021-05-15 18:57 UTC, shoggy commented on src/test/java/ru/training/at/hw3/ExerciseOne.java
> +    }
Please parameterize methods in the following way
```java
public test() {
    openSiteByUrlTest(DataStore.getProperty("siteUrl"), DataStore.getProperty("browserTitle"));
    performLoginTest(DataStore.getProperty("userName"), DataStore.getProperty("password"), DataStore.getProperty("userNameAfterLogged"));
...
}

private void openSiteByUrlTest(final String siteUrl, final String expectedTitle) {
    driver.navigate().to(siteUrl);
    softAssert.assertEquals(driver.getTitle(), expectedTitle);
}

private void performLoginTest(String userName, String password, String expectedUserName) {
    loginPage.clickImgUser();
    loginPage.inputFieldLogin(userName);

    loginPage.inputFieldPassword(password);
    loginPage.clickBtnEnter();
    String actualUserNameAfterLogged = loginPage.getUserName();
    softAssert.assertEquals(actualUserNameAfterLogged, expectedUserName);
}

```

Other methods that are called from `@Test` method should be refactored in the same way

2021-05-15 19:15 UTC, iRezograf commented on src/test/java/ru/training/at/hw3/pageobjects/LoginPage.java
> +        wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//*[@id='user-name']")));
public String getUserName() {
        WebDriverWait wait = new WebDriverWait(driver, 10);
        wait.until(ExpectedConditions.visibilityOf(loggedUserName));
        String userName = loggedUserName.getText();
        return userName;
    }

2021-05-15 19:23 UTC, shoggy commented on src/test/java/ru/training/at/hw3/ExerciseOne.java
> +        driver = new ChromeDriver();
Let's move this to a separate class

2021-05-15 19:23 UTC, iRezograf commented on src/test/java/ru/training/at/hw3/pageobjects/DifferentElementsPage.java
> +    }
Нет, она возвращает одну сконкатенированную строку, Точнее List c одной строкой.

2021-05-16 08:30 UTC, iRezograf commented on src/test/java/ru/training/at/hw3/pageobjects/BenefitIcon.java
> +    private WebElement benefitBase;
@Getter
public class BenefitIcon {
    public WebDriver driver;

    @FindBy(css = ".benefit-icon")
    private List<WebElement> benefitIcons;

    public BenefitIcon(WebDriver driver) {
        PageFactory.initElements(driver, this);
        this.driver = driver;
    }
}

2021-05-16 10:00 UTC, iRezograf commented on src/test/java/ru/training/at/hw3/pageobjects/DifferentElementsPage.java
> +    WebElement stringWater;
@FindBy(xpath = "//*[@class='panel-body-list logs']/li")
    List<WebElement> logList;

    public List<String> getLogListAsString() {
        List<String> list = new ArrayList<>();
        for (WebElement element : logList) {
            list.add(element.getText());
        }
        return list;
    }

2021-05-16 10:00 UTC, iRezograf commented on src/test/java/ru/training/at/hw3/pageobjects/BenefitText.java
> +    WebElement benefitBase;
@Getter
public class Benefits {
    public WebDriver driver;

    @FindBy(css = ".benefit-icon")
    private List<WebElement> benefitIcons;

    @FindBy(css = ".benefit-txt")
    private List<WebElement> benefitTxt;


    public Benefits(WebDriver driver) {
        PageFactory.initElements(driver, this);
        this.driver = driver;
    }

    public List<String> getBenefitTxtAsString() {
        List<String> list = new ArrayList<>();
        for (WebElement element : benefitTxt) {
            list.add(element.getText());
        }
        return list;
    }
}

2021-05-16 10:01 UTC, iRezograf commented on src/test/java/ru/training/at/hw3/pageobjects/BenefitText.java
> +    }
@Getter
public class Benefits {
    public WebDriver driver;

    @FindBy(css = ".benefit-icon")
    private List<WebElement> benefitIcons;

    @FindBy(css = ".benefit-txt")
    private List<WebElement> benefitTxt;


    public Benefits(WebDriver driver) {
        PageFactory.initElements(driver, this);
        this.driver = driver;
    }

    public List<String> getBenefitTxtAsString() {
        List<String> list = new ArrayList<>();
        for (WebElement element : benefitTxt) {
            list.add(element.getText());
        }
        return list;
    }
}

2021-05-16 10:04 UTC, iRezograf commented on src/test/java/ru/training/at/hw3/pageobjects/DifferentElementsPage.java
> +    }
@FindBy(xpath = "//*[@class='panel-body-list logs']/li")
List<WebElement> logList;

public List<String> getLogListAsString() {
    List<String> list = new ArrayList<>();
    for (WebElement element : logList) {
        list.add(element.getText());
    }
    return list;
}

2021-05-16 10:35 UTC, iRezograf commented on src/test/java/ru/training/at/hw3/ExerciseOne.java
> +        driver = new ChromeDriver();
package ru.training.at.hw3.util;

import io.github.bonigarcia.wdm.WebDriverManager;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import static io.github.bonigarcia.wdm.config.DriverManagerType.CHROME;

public class DriverManager {
    WebDriver driver;

    public WebDriver setup() {
        WebDriverManager.getInstance(CHROME).setup();
        driver = new ChromeDriver();
        return driver;
    }
}

2021-05-16 12:15 UTC, iRezograf commented on src/test/java/ru/training/at/hw3/ExerciseOne.java
> +    }
@Test(groups = {"exercise_hw3.1"})
    public void allExerciseOneTest() {
        openSiteByUrlTest(
                DataStore.getProperty("siteUrl"),
                DataStore.getProperty("browserTitle"));

        performLoginTest(
                DataStore.getProperty("userName"),
                DataStore.getProperty("password"),
                DataStore.getProperty("userNameAfterLogged"));

        headerHaveProperTextsTest(
                getActualHeaderMenuItemHome(),
                getExpectedHeaderMenuItemHome());

        fourIconsInHomePageExistsTest(benefits.getBenefitIcons());

        fourTextsOnTheIndexPageUnderIconsAndTheyHaveProperTextTest(
                benefits.getBenefitTxtAsString(),
                getExpectedTextsOnTheIndexPageUnderIconsAndTheyHaveProperText());
        iframeWithFrameButtonExistTest(framePage);
        thereIsFrameButtonInTheIframeTest(framePage);
        switchToOriginalWindowBackTest(DataStore.getProperty("browserTitle"));
        thereAreFiveItemsInTheLeftSectionTest(
                leftMenu.getLeftMenuAsString(),
                getExceptedFiveItemsInTheLeftSection());
    }

2021-05-17 18:23 UTC, shoggy approved these changes
Good job!

2021-05-17 18:49 UTC, merged