Hw4
iRezograf/Rafael_Reziapov pull request #11
Opened 2021-05-19 17:16 UTC by iRezograf

Integration with Jenkins have done.  Listener didn't create. I'm working on it.

2021-05-20 20:14 UTC, iRezograf commented
![image](https://user-images.githubusercontent.com/23257075/119042902-207fb880-b9c1-11eb-8af1-0b73d3b15464.png)

2021-05-21 17:26 UTC, iRezograf commented
softAssert.assertAll() moved into allExerciseOne /(Two) Test.

Before/AfterClass changed on Before/AfterMethod

2021-05-22 13:34 UTC, shoggy requested changes
According to task working ex1, working ex2, and failing ex1 should exist
`@Feature` and `@Story` annotations use is required

2021-05-22 13:34 UTC, shoggy commented on src/test/java/ru/training/at/hw4/ExerciseOne.java
> +        driver = driverManager.setup();
the driver should be placed into context after its initialization (firstly create driver, secondly put it into the context)

same for other test class

2021-05-22 14:37 UTC, iRezograf commented on src/test/java/ru/training/at/hw4/ExerciseOne.java
> +        driver = driverManager.setup();
context.setAttribute("driver", driver); was moved to place after initialisation driver

@Feature and @ Story added

2021-05-22 14:38 UTC, iRezograf commented on src/test/java/ru/training/at/hw4/ExerciseOne.java
> +        driver = driverManager.setup();
![image](https://user-images.githubusercontent.com/23257075/119230361-8042a480-bb24-11eb-9eb0-634ddbea8dcf.png)

2021-05-24 09:48 UTC, shoggy approved these changes

2021-05-24 10:13 UTC, merged