Hw6
iRezograf/Rafael_Reziapov pull request #13
Opened 2021-06-01 21:11 UTC by iRezograf

Please aprove it.

2021-06-03 11:02 UTC, shoggy requested changes

2021-06-03 11:02 UTC, shoggy commented on pom.xml
> +        </dependency>
duplicated dependency

2021-06-03 11:02 UTC, shoggy commented on src/test/java/ru/training/at/hw6/interfaces/TestsInit.java
> +public interface TestsInit {
Initially interface is not intended for such useage

2021-06-03 11:02 UTC, shoggy commented on src/main/java/ru/training/at/hw6/providers/JsonDataParser.java
> +
Input data parsing depends not only on the data itself, but also on external config values

2021-06-03 11:05 UTC, shoggy commented on src/test/java/ru/training/at/hw6/JdiTests.java
> +    }
This should be implemented using `com.epam.jdi.light.elements.composite.Form`

2021-06-03 20:06 UTC, iRezograf commented on pom.xml
> +        </dependency>
done

2021-06-03 20:13 UTC, iRezograf commented on src/test/java/ru/training/at/hw6/interfaces/TestsInit.java
> +public interface TestsInit {
Replaced by:
public class JdiTests extends TestsInit{

2021-06-05 14:04 UTC, iRezograf commented on src/test/java/ru/training/at/hw6/interfaces/TestsInit.java
> +public interface TestsInit {
Included into^
public class JdiTests {
    LoginUserData loginUserData;

    @BeforeSuite(alwaysRun = true)
    static void beforeSuite() {
        PageFactory.initElements(SiteJdi.class);
    }

    @AfterSuite(alwaysRun = true)
    static void afterSuite() {
        WebDriverUtils.killAllSeleniumDrivers();
    }

2021-06-06 03:14 UTC, iRezograf commented on src/test/java/ru/training/at/hw6/JdiTests.java
> +    }
done

2021-06-06 03:14 UTC, iRezograf commented on src/main/java/ru/training/at/hw6/providers/JsonDataParser.java
> +
done

2021-06-08 06:45 UTC, shoggy requested changes

2021-06-08 06:45 UTC, shoggy commented on src/main/java/ru/training/at/hw6/forms/LoginForm.java
> +public class LoginForm {
Form should extend Form

2021-06-08 06:45 UTC, shoggy commented on src/main/java/ru/training/at/hw6/forms/LoginForm.java
> +    }
please refer to `com.epam.jdi.light.elements.composite.Form#login(T)`

2021-06-08 06:45 UTC, shoggy commented on src/main/java/ru/training/at/hw6/forms/MetalsAndColorsForm.java
> +public class MetalsAndColorsForm  {
This class should extend Form

2021-06-08 06:45 UTC, shoggy commented on src/test/java/ru/training/at/hw6/JdiTests.java
> +    }
This method should be in corresponding form class, 
please look for `com.epam.jdi.light.elements.composite.Form#fill(T)` or `com.epam.jdi.light.elements.composite.Form#submit(T)`

2021-06-08 12:12 UTC, iRezograf commented on src/main/java/ru/training/at/hw6/forms/LoginForm.java
> +public class LoginForm {
done

2021-06-08 12:14 UTC, iRezograf commented on src/main/java/ru/training/at/hw6/forms/LoginForm.java
> +    }
refered but didn't find something wrong

2021-06-08 12:14 UTC, iRezograf commented on src/test/java/ru/training/at/hw6/JdiTests.java
> +    }
done

2021-06-10 12:40 UTC, shoggy approved these changes

2021-06-10 18:00 UTC, merged