Homework 2
iRezograf/Rafael_Reziapov pull request #9
Opened 2021-05-10 15:21 UTC by iRezograf

Vladimir, HW2 is done. Approve it, please

2021-05-10 22:59 UTC, shoggy requested changes
Please apply comments to all applicable places (I tried to put one comment for the first appearance of the issue, but other appearances should be fixed in the same way)

2021-05-10 22:59 UTC, shoggy commented on pom.xml
> +        </dependency>
This is something veeery old. Please remove it

2021-05-10 22:59 UTC, shoggy commented on pom.xml
> +            <version>${selenium.webdriver.common.version}</version>
please add `scope:test`

2021-05-10 22:59 UTC, shoggy commented on src/test/java/ru/training/at/hw2/ex1/ExerciseOne.java
> +import static org.testng.AssertJUnit.assertEquals;
Please remove unused imports
If you use IntelliJ IDEA, the `Ctrl+Alt+O` shortcut can be used

2021-05-10 22:59 UTC, shoggy commented on src/test/java/ru/training/at/hw2/ex1/ExerciseOne.java
> +
Please refactor test methods in the following way
1. create one method, annotate it with `@Test`
2. remove test annotation from all other methods
3. sequentially call old test methods from the new one
4. do not forget to check that `softAssert` does not contain any failures

something like
```java
@Test
public void someTestName() {
  openSiteByUrlTest();
  browserTitleTest();
  ...
  // check softAssert
}
```

2021-05-10 22:59 UTC, shoggy commented on src/test/java/ru/training/at/hw2/ex1/ExerciseOne.java
> +        driverPath = "C:\\Users\\rezog\\driver\\chromedriver.exe";
Test is machine-dependent
Consider the use of bonigarcia webdrivermanager or put chromedriver in the project

2021-05-10 22:59 UTC, shoggy commented on src/test/java/ru/training/at/hw2/ex1/ExerciseOne.java
> +        ExpectedConditions.textToBePresentInElement(element, "ROMAN IOVLEV!");
I think this statement is extra here, please remove it

This statement creates `ExpectedCondition` object that can be used in `org.openqa.selenium.support.ui.Wait` (explicit waits) but do not wait itself

2021-05-10 22:59 UTC, shoggy commented on src/test/java/ru/training/at/hw2/ex1/ExerciseOne.java
> +        List<WebElement> elements = driver.findElements(By.tagName("li")).subList(0, 3);
Why it is a sublist?

2021-05-10 22:59 UTC, shoggy commented on src/test/java/ru/training/at/hw2/ex1/ExerciseOne.java
> +        softAssert.assertEquals(element.getText(), "METALS & COLORS");
Why this item selector significantly differs from the other three?

2021-05-10 22:59 UTC, shoggy commented on src/test/java/ru/training/at/hw2/ex1/ExerciseOne.java
> +                "/html/body/header/div/nav/ul[1]/li[4]/a"));
Please try to not use generated locators
locator that you used for "Metal and Colors" is almost right, correct it a bit

2021-05-10 22:59 UTC, shoggy commented on src/test/java/ru/training/at/hw2/ex1/ExerciseOne.java
> +        WebElement iframe = driver.findElement(By.xpath(iframeWithFrameButton));
Please use id `frame` or CSS `iframe#frame` for By definition and search of element

2021-05-10 22:59 UTC, shoggy commented on src/test/java/ru/training/at/hw2/ex2/ExerciseTwo.java
> +        "div.main-content > div > div:nth-child(2) >label:nth-child(1)"));
Try to not use indices in selectors (sometimes it is acceptable, but in most cases, they can be avoided by use of the other selector e.g. by specifying class, tag ,input type)

2021-05-11 07:27 UTC, iRezograf commented on pom.xml
> +        </dependency>
Done

2021-05-11 07:34 UTC, iRezograf commented on pom.xml
> +            <version>${selenium.webdriver.common.version}</version>
I have deleted it

2021-05-11 07:37 UTC, iRezograf commented on src/test/java/ru/training/at/hw2/ex1/ExerciseOne.java
> +import static org.testng.AssertJUnit.assertEquals;
Done

2021-05-11 08:21 UTC, iRezograf commented on src/test/java/ru/training/at/hw2/ex1/ExerciseOne.java
> +        driverPath = "C:\\Users\\rezog\\driver\\chromedriver.exe";
Done

2021-05-11 09:53 UTC, iRezograf commented on src/test/java/ru/training/at/hw2/ex1/ExerciseOne.java
> +        List<WebElement> elements = driver.findElements(By.tagName("li")).subList(0, 3);
Fixed with:
element = driver.findElement(By.cssSelector(
                "ul.uui-navigation.nav.navbar-nav.m-l8 >li:nth-child(1)"));
        Assert.assertEquals(element.getText(), "HOME");
        Assert.assertTrue(element.isDisplayed());

        element = driver.findElement(By.cssSelector(
                "ul.uui-navigation.nav.navbar-nav.m-l8 >li:nth-child(2)"));
        Assert.assertEquals(element.getText(), "CONTACT FORM");
        Assert.assertTrue(element.isDisplayed());

        element = driver.findElement(By.cssSelector(
                "ul.uui-navigation.nav.navbar-nav.m-l8 >li:nth-child(3)"));
        Assert.assertEquals(element.getText(), "SERVICE");
        Assert.assertTrue(element.isDisplayed());

        element = driver.findElement(By.cssSelector(
                "ul.uui-navigation.nav.navbar-nav.m-l8>li:nth-child(4)"));
        Assert.assertEquals(element.getText(), "METALS & COLORS");
        Assert.assertTrue(element.isDisplayed());

2021-05-11 09:54 UTC, iRezograf commented on src/test/java/ru/training/at/hw2/ex1/ExerciseOne.java
> +        WebElement iframe = driver.findElement(By.xpath(iframeWithFrameButton));
Fixed with:
element = driver.findElement(By.cssSelector(
                "ul.uui-navigation.nav.navbar-nav.m-l8 >li:nth-child(1)"));
        Assert.assertEquals(element.getText(), "HOME");
        Assert.assertTrue(element.isDisplayed());

        element = driver.findElement(By.cssSelector(
                "ul.uui-navigation.nav.navbar-nav.m-l8 >li:nth-child(2)"));
        Assert.assertEquals(element.getText(), "CONTACT FORM");
        Assert.assertTrue(element.isDisplayed());

        element = driver.findElement(By.cssSelector(
                "ul.uui-navigation.nav.navbar-nav.m-l8 >li:nth-child(3)"));
        Assert.assertEquals(element.getText(), "SERVICE");
        Assert.assertTrue(element.isDisplayed());

        element = driver.findElement(By.cssSelector(
                "ul.uui-navigation.nav.navbar-nav.m-l8>li:nth-child(4)"));
        Assert.assertEquals(element.getText(), "METALS & COLORS");
        Assert.assertTrue(element.isDisplayed());

2021-05-11 17:46 UTC, iRezograf commented on src/test/java/ru/training/at/hw2/ex2/ExerciseTwo.java
> +        "div.main-content > div > div:nth-child(2) >label:nth-child(1)"));
Done

2021-05-11 17:47 UTC, iRezograf commented
I fixed all remarks.

2021-05-11 17:53 UTC, iRezograf commented on src/test/java/ru/training/at/hw2/ex1/ExerciseOne.java
> +        ExpectedConditions.textToBePresentInElement(element, "ROMAN IOVLEV!");
Deleted

2021-05-12 09:53 UTC, shoggy requested changes

2021-05-12 09:53 UTC, shoggy commented on src/test/java/ru/training/at/hw2/ex1/ExerciseOne.java
> +        }
Would be better to use not hardcoded values for iteration
```suggestion
        for (int i = 0; i < getTextOfHeaderMenuButtonsList().size(); i++) {
            element = driver.findElement(By.cssSelector(
                    "ul.uui-navigation.nav.navbar-nav.m-l8 >li:nth-child(" + (i + 1) + ")"));
            Assert.assertEquals(element.getText(),
                    dp.getTextOfHeaderMenuButtonsList().get(i));
        }
```

\+ same for `fourTextsOnTheIndexPageUnderIconsAndTheyHaveProperTextTest` and `thereAreFiveItemsInTheLeftSectionTest()`

2021-05-12 09:53 UTC, shoggy commented on src/test/java/ru/training/at/hw2/ex2/ExerciseTwo.java
> +                "ul.uui-navigation.nav.navbar-nav.m-l8>li.dropdown>ul li:nth-child(8)"));
In this case would be better to discard the use of indices, and replace it with search by text or by href 
```suggestion
                "ul.uui-navigation.nav.navbar-nav.m-l8>li.dropdown>ul li a[href='different-elements.html']"));
```

2021-05-12 09:53 UTC, shoggy commented on src/test/java/ru/training/at/hw2/ex2/ExerciseTwo.java
> +                "div.main-content > div > div:nth-child(2)>label:nth-child(1)"));
At least block of inputs should be found without indices

2021-05-12 14:27 UTC, shoggy approved these changes

2021-05-12 14:38 UTC, merged